name = "tts-voice-magic"
main = "index.js"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]  # 注意逗号分隔（之前漏了逗号）

# 静态资源配置（核心修正：单括号 [assets] → 双括号 [[assets]]）
[assets]  # 双括号表示数组项，这是 Cloudflare 要求的格式
binding = "ASSETS"  # 固定绑定名称（必须大写）
directory = "./public"  # 静态文件目录

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[env.production]
name = "tts-voice-magic"
routes = ["https://tts.ityxx.cn/*"]

[env.development]
routes = ["http://localhost:8787/*"]

[env.staging]
name = "tts-voice-magic-staging"

[vars]
# 环境变量

# （可选）KV 存储
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

[triggers]
crons = []